/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JInternalFrame.java to edit this template
 */
package GUI;

import com.mycompany.aplicacion_de_conceptos.servicios.ServicioEstudiante;
import com.mycompany.aplicacion_de_conceptos.fabricas.FabricaExterior;
import com.mycompany.aplicacion_de_conceptos.dtos.DTOEstudiante;
import com.mycompany.aplicacion_de_conceptos.dtos.DTOPrograma;
import com.mycompany.aplicacion_de_conceptos.servicios.ServicioPrograma;

import java.util.List;

/**
 *
 * @author getro
 */
public class Estudiante extends javax.swing.JInternalFrame {

    /**
     * Creates new form Estudiante
     */
    public Estudiante() {
        initComponents();
        this.servicioEstudiante = FabricaExterior.obtenerServicioEstudiante();
        this.servicioPrograma = FabricaExterior.obtenerServicioPrograma();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        Estado = new javax.swing.ButtonGroup();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        numero_identificacion = new javax.swing.JTextField();
        nombres = new javax.swing.JTextField();
        Apellidos = new javax.swing.JTextField();
        correo = new javax.swing.JTextField();
        codigo = new javax.swing.JTextField();
        promedio = new javax.swing.JTextField();
        programa = new javax.swing.JComboBox<>();
        Actualizar_Programas = new javax.swing.JButton();
        Activo = new javax.swing.JRadioButton();
        Desactivo = new javax.swing.JRadioButton();
        Guardar = new javax.swing.JButton();
        Eliminar = new javax.swing.JButton();
        buscar_identificacion = new javax.swing.JButton();

        setClosable(true);
        setIconifiable(true);
        setMaximizable(true);
        setTitle("Esudiante");

        jLabel1.setText("Numero de identificacion :");

        jLabel2.setText("Nombres :");

        jLabel3.setText("Apellidos :");

        jLabel4.setText("Correo Electronico :");

        jLabel5.setText("Codigo Estudiantil :");

        jLabel6.setText("Programa :");

        jLabel7.setText("Estado :");

        jLabel8.setText("Promedio :");

        programa.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { " ", " " }));

        Actualizar_Programas.setText("Actualizar");
        Actualizar_Programas.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Actualizar_ProgramasActionPerformed(evt);
            }
        });

        Estado.add(Activo);
        Activo.setText("Activo");

        Estado.add(Desactivo);
        Desactivo.setText("Desactivo");

        Guardar.setText("Guardar");
        Guardar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                GuardarActionPerformed(evt);
            }
        });

        Eliminar.setText("Eliminar");
        Eliminar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                EliminarActionPerformed(evt);
            }
        });

        buscar_identificacion.setText("Buscar");
        buscar_identificacion.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                buscar_identificacionActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel1)
                            .addComponent(jLabel2, javax.swing.GroupLayout.Alignment.TRAILING))
                        .addGroup(layout.createSequentialGroup()
                            .addGap(87, 87, 87)
                            .addComponent(jLabel3)))
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addComponent(jLabel4)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jLabel6)
                            .addComponent(jLabel5)
                            .addComponent(jLabel7)
                            .addComponent(jLabel8))))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(Guardar)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(Eliminar))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(promedio, javax.swing.GroupLayout.DEFAULT_SIZE, 233, Short.MAX_VALUE)
                            .addComponent(codigo, javax.swing.GroupLayout.DEFAULT_SIZE, 233, Short.MAX_VALUE)
                            .addComponent(correo, javax.swing.GroupLayout.DEFAULT_SIZE, 233, Short.MAX_VALUE)
                            .addComponent(Apellidos, javax.swing.GroupLayout.DEFAULT_SIZE, 233, Short.MAX_VALUE)
                            .addComponent(nombres, javax.swing.GroupLayout.DEFAULT_SIZE, 233, Short.MAX_VALUE)
                            .addComponent(programa, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(numero_identificacion))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(Actualizar_Programas, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(buscar_identificacion, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(Activo)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(Desactivo))))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(numero_identificacion, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(buscar_identificacion))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(nombres, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(Apellidos, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel4)
                    .addComponent(correo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel5)
                    .addComponent(codigo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel6)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(programa, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(Actualizar_Programas)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel7)
                    .addComponent(Activo)
                    .addComponent(Desactivo))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel8)
                    .addComponent(promedio, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(Guardar)
                    .addComponent(Eliminar))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents
    private Observable observable = new Observable();

    public void agregarObservador(Observador o) {
        observable.agregarObservador(o);
    }
    
    
    private void EliminarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_EliminarActionPerformed
        servicioEstudiante.eliminarEstudiante(numero_identificacion.getText());
        observable.notificarObservadores("Estudiante", "guardar", this);
    }//GEN-LAST:event_EliminarActionPerformed

    private void GuardarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_GuardarActionPerformed
        double id = Double.parseDouble(numero_identificacion.getText());
        double Codigo = Double.parseDouble(codigo.getText());
        boolean estado;
        double Promedio = Double.parseDouble(promedio.getText());
        String seleccion = (String) programa.getSelectedItem();
        DTOPrograma Programa = servicioPrograma.obtenerPrograma(seleccion);
        if(Activo.isSelected()){
            estado = true;
        }else{
            estado = false;
        }
        DTOEstudiante estudiante = FabricaExterior.obtenerEstudianteDTO(id, nombres.getText(), Apellidos.getText(),
                correo.getText(),Codigo,Programa, estado, Promedio);
        servicioEstudiante.InscribirEstudiante(estudiante);
        observable.notificarObservadores("Estudiante", "eliminar", this);
    }//GEN-LAST:event_GuardarActionPerformed

    private void Actualizar_ProgramasActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Actualizar_ProgramasActionPerformed
        List<DTOPrograma> Programas = servicioPrograma.obtenerProgramas();
        programa.removeAllItems(); // Limpiar antes de llenar

        for (DTOPrograma programaDTO : Programas) {
            programa.addItem(String.valueOf(programaDTO.getId()));
        }
    }//GEN-LAST:event_Actualizar_ProgramasActionPerformed

    private void buscar_identificacionActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_buscar_identificacionActionPerformed
        DTOEstudiante estudiante = servicioEstudiante.obtenerEstudiante(numero_identificacion.getText());
        nombres.setText(estudiante.getNombres());
        Apellidos.setText(estudiante.getApellidos());
        correo.setText(estudiante.getEmail());
        codigo.setText(String.valueOf(estudiante.getCodigo()));
        if(estudiante.isActivo() == true){
            Activo.doClick();
        }else{
           Desactivo.doClick();
        }
        promedio.setText(String.valueOf(estudiante.getPromedio()));
        programa.removeAllItems();
        programa.addItem(String.valueOf(estudiante.getPrograma().getId()));
    }//GEN-LAST:event_buscar_identificacionActionPerformed

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JRadioButton Activo;
    private javax.swing.JButton Actualizar_Programas;
    private javax.swing.JTextField Apellidos;
    private javax.swing.JRadioButton Desactivo;
    private javax.swing.JButton Eliminar;
    private javax.swing.ButtonGroup Estado;
    private javax.swing.JButton Guardar;
    private javax.swing.JButton buscar_identificacion;
    private javax.swing.JTextField codigo;
    private javax.swing.JTextField correo;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JTextField nombres;
    private javax.swing.JTextField numero_identificacion;
    private javax.swing.JComboBox<String> programa;
    private javax.swing.JTextField promedio;
    // End of variables declaration//GEN-END:variables
    ServicioEstudiante servicioEstudiante;
    ServicioPrograma servicioPrograma;
}

