/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package GUI;

import java.awt.BorderLayout;
import javax.swing.JPanel;
import GUI.Incribir_Persona;

/**
 *
 * @author getro
 */
public class GIU_Principal extends javax.swing.JFrame {

    /**
     * Creates new form GIU_Principal
     */
    public GIU_Principal() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        HOME = new javax.swing.JTabbedPane();
        Home = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        PersonasInscritas = new javax.swing.JPanel();
        content_PersonasInscritas = new javax.swing.JPanel();
        Inscribir_Persona = new javax.swing.JToggleButton();
        Eliminar_Persona = new javax.swing.JToggleButton();
        Actualizar_Persona = new javax.swing.JToggleButton();
        CursosProfesores = new javax.swing.JPanel();
        content_CursosProfesores = new javax.swing.JPanel();
        Inscribir_Profesores = new javax.swing.JToggleButton();
        toString_Profesores = new javax.swing.JButton();
        CursosInscritos = new javax.swing.JPanel();
        content_CusosInscritos = new javax.swing.JPanel();
        Inscribir_Cursos = new javax.swing.JButton();
        Eliminar_Cursos = new javax.swing.JButton();
        Actualizar_Cursos = new javax.swing.JButton();
        toString = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLabel1.setText("holiiii");

        javax.swing.GroupLayout HomeLayout = new javax.swing.GroupLayout(Home);
        Home.setLayout(HomeLayout);
        HomeLayout.setHorizontalGroup(
            HomeLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(HomeLayout.createSequentialGroup()
                .addGap(214, 214, 214)
                .addComponent(jLabel1)
                .addContainerGap(705, Short.MAX_VALUE))
        );
        HomeLayout.setVerticalGroup(
            HomeLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, HomeLayout.createSequentialGroup()
                .addContainerGap(275, Short.MAX_VALUE)
                .addComponent(jLabel1)
                .addGap(259, 259, 259))
        );

        HOME.addTab("HOME", Home);

        javax.swing.GroupLayout content_PersonasInscritasLayout = new javax.swing.GroupLayout(content_PersonasInscritas);
        content_PersonasInscritas.setLayout(content_PersonasInscritasLayout);
        content_PersonasInscritasLayout.setHorizontalGroup(
            content_PersonasInscritasLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 778, Short.MAX_VALUE)
        );
        content_PersonasInscritasLayout.setVerticalGroup(
            content_PersonasInscritasLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
        );

        Inscribir_Persona.setLabel("Incribir");
        Inscribir_Persona.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Inscribir_PersonaActionPerformed(evt);
            }
        });

        Eliminar_Persona.setLabel("Eliminar");
        Eliminar_Persona.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Eliminar_PersonaActionPerformed(evt);
            }
        });

        Actualizar_Persona.setLabel("Actualizar");
        Actualizar_Persona.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Actualizar_PersonaActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout PersonasInscritasLayout = new javax.swing.GroupLayout(PersonasInscritas);
        PersonasInscritas.setLayout(PersonasInscritasLayout);
        PersonasInscritasLayout.setHorizontalGroup(
            PersonasInscritasLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, PersonasInscritasLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(PersonasInscritasLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(Eliminar_Persona, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(Actualizar_Persona, javax.swing.GroupLayout.DEFAULT_SIZE, 111, Short.MAX_VALUE)
                    .addComponent(Inscribir_Persona, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 54, Short.MAX_VALUE)
                .addComponent(content_PersonasInscritas, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
        );
        PersonasInscritasLayout.setVerticalGroup(
            PersonasInscritasLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(PersonasInscritasLayout.createSequentialGroup()
                .addComponent(content_PersonasInscritas, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
            .addGroup(PersonasInscritasLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(Inscribir_Persona)
                .addGap(18, 18, 18)
                .addComponent(Eliminar_Persona)
                .addGap(18, 18, 18)
                .addComponent(Actualizar_Persona)
                .addContainerGap(439, Short.MAX_VALUE))
        );

        Inscribir_Persona.getAccessibleContext().setAccessibleName("Inscribir");

        HOME.addTab("Personas Inscritas", PersonasInscritas);

        content_CursosProfesores.setPreferredSize(new java.awt.Dimension(778, 544));

        javax.swing.GroupLayout content_CursosProfesoresLayout = new javax.swing.GroupLayout(content_CursosProfesores);
        content_CursosProfesores.setLayout(content_CursosProfesoresLayout);
        content_CursosProfesoresLayout.setHorizontalGroup(
            content_CursosProfesoresLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 778, Short.MAX_VALUE)
        );
        content_CursosProfesoresLayout.setVerticalGroup(
            content_CursosProfesoresLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
        );

        Inscribir_Profesores.setLabel("Inscribir");
        Inscribir_Profesores.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Inscribir_ProfesoresActionPerformed(evt);
            }
        });

        toString_Profesores.setLabel("toString");
        toString_Profesores.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                toString_ProfesoresActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout CursosProfesoresLayout = new javax.swing.GroupLayout(CursosProfesores);
        CursosProfesores.setLayout(CursosProfesoresLayout);
        CursosProfesoresLayout.setHorizontalGroup(
            CursosProfesoresLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, CursosProfesoresLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(CursosProfesoresLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(Inscribir_Profesores, javax.swing.GroupLayout.DEFAULT_SIZE, 111, Short.MAX_VALUE)
                    .addComponent(toString_Profesores, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 54, Short.MAX_VALUE)
                .addComponent(content_CursosProfesores, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
        );
        CursosProfesoresLayout.setVerticalGroup(
            CursosProfesoresLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(CursosProfesoresLayout.createSequentialGroup()
                .addComponent(content_CursosProfesores, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
            .addGroup(CursosProfesoresLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(Inscribir_Profesores)
                .addGap(18, 18, 18)
                .addComponent(toString_Profesores)
                .addContainerGap(480, Short.MAX_VALUE))
        );

        HOME.addTab("Cursos Profesores", CursosProfesores);

        content_CusosInscritos.setPreferredSize(new java.awt.Dimension(778, 544));

        javax.swing.GroupLayout content_CusosInscritosLayout = new javax.swing.GroupLayout(content_CusosInscritos);
        content_CusosInscritos.setLayout(content_CusosInscritosLayout);
        content_CusosInscritosLayout.setHorizontalGroup(
            content_CusosInscritosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 778, Short.MAX_VALUE)
        );
        content_CusosInscritosLayout.setVerticalGroup(
            content_CusosInscritosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
        );

        Inscribir_Cursos.setLabel("Inscribir");
        Inscribir_Cursos.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Inscribir_CursosActionPerformed(evt);
            }
        });

        Eliminar_Cursos.setLabel("Eliminar");

        Actualizar_Cursos.setLabel("Actualizar");

        toString.setActionCommand("toString");
        toString.setLabel("toString");

        javax.swing.GroupLayout CursosInscritosLayout = new javax.swing.GroupLayout(CursosInscritos);
        CursosInscritos.setLayout(CursosInscritosLayout);
        CursosInscritosLayout.setHorizontalGroup(
            CursosInscritosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, CursosInscritosLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(CursosInscritosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(Inscribir_Cursos, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(Eliminar_Cursos, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(Actualizar_Cursos, javax.swing.GroupLayout.DEFAULT_SIZE, 111, Short.MAX_VALUE)
                    .addComponent(toString, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 54, Short.MAX_VALUE)
                .addComponent(content_CusosInscritos, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
        );
        CursosInscritosLayout.setVerticalGroup(
            CursosInscritosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(CursosInscritosLayout.createSequentialGroup()
                .addComponent(content_CusosInscritos, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
            .addGroup(CursosInscritosLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(Inscribir_Cursos)
                .addGap(18, 18, 18)
                .addComponent(Eliminar_Cursos)
                .addGap(18, 18, 18)
                .addComponent(Actualizar_Cursos)
                .addGap(18, 18, 18)
                .addComponent(toString)
                .addContainerGap(398, Short.MAX_VALUE))
        );

        HOME.addTab("Cursos Inscritos", CursosInscritos);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(HOME)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(HOME)
        );

        HOME.getAccessibleContext().setAccessibleName("HOME");

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void ShowPanel(JPanel panel,JPanel content){
        panel.setSize(778, 544);
        panel.setLocation(0,0);
        
        content.removeAll();
        content.add(panel, BorderLayout.CENTER);
        content.revalidate();
        content.repaint();
    }
    
    
    private void Inscribir_PersonaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Inscribir_PersonaActionPerformed
        Incribir_Persona Panel = new Incribir_Persona ();
        ShowPanel(Panel ,content_PersonasInscritas);
    }//GEN-LAST:event_Inscribir_PersonaActionPerformed

    private void Eliminar_PersonaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Eliminar_PersonaActionPerformed
        Eliminar_Persona Panel = new Eliminar_Persona();
        ShowPanel(Panel,content_PersonasInscritas);
    }//GEN-LAST:event_Eliminar_PersonaActionPerformed

    private void Actualizar_PersonaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Actualizar_PersonaActionPerformed
        Actualizar_Persona Panel = new Actualizar_Persona();
        ShowPanel(Panel,content_PersonasInscritas);
    }//GEN-LAST:event_Actualizar_PersonaActionPerformed

    private void Inscribir_ProfesoresActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Inscribir_ProfesoresActionPerformed
        Inscribir_Profesores Panel = new Inscribir_Profesores();
        ShowPanel(Panel,content_CursosProfesores);
    }//GEN-LAST:event_Inscribir_ProfesoresActionPerformed

    private void toString_ProfesoresActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_toString_ProfesoresActionPerformed
        toString_Profesores Panel = new toString_Profesores();
        ShowPanel(Panel,content_CursosProfesores);
    }//GEN-LAST:event_toString_ProfesoresActionPerformed

    private void Inscribir_CursosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Inscribir_CursosActionPerformed
        Inscribir_Inscripcion Panel = new Inscribir_Inscripcion();
        ShowPanel(Panel,content_CusosInscritos);
    }//GEN-LAST:event_Inscribir_CursosActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(GIU_Principal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(GIU_Principal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(GIU_Principal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(GIU_Principal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new GIU_Principal().setVisible(true);
            }
        });
    }
    
    

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton Actualizar_Cursos;
    private javax.swing.JToggleButton Actualizar_Persona;
    private javax.swing.JPanel CursosInscritos;
    private javax.swing.JPanel CursosProfesores;
    private javax.swing.JButton Eliminar_Cursos;
    private javax.swing.JToggleButton Eliminar_Persona;
    private javax.swing.JTabbedPane HOME;
    private javax.swing.JPanel Home;
    private javax.swing.JButton Inscribir_Cursos;
    private javax.swing.JToggleButton Inscribir_Persona;
    private javax.swing.JToggleButton Inscribir_Profesores;
    private javax.swing.JPanel PersonasInscritas;
    private javax.swing.JPanel content_CursosProfesores;
    private javax.swing.JPanel content_CusosInscritos;
    private javax.swing.JPanel content_PersonasInscritas;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JButton toString;
    private javax.swing.JButton toString_Profesores;
    // End of variables declaration//GEN-END:variables
}
