/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package com.mycompany.aplicacion_de_conceptos.GUI;

import java.awt.BorderLayout;
import javax.swing.JPanel;

/**
 *
 * @author getro
 */
public class GIU_Principal extends javax.swing.JFrame {

    /**
     * Creates new form GIU_Principal
     */
    public GIU_Principal() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        HOME = new javax.swing.JTabbedPane();
        Home = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        PersonasInscritas = new javax.swing.JPanel();
        content_PersonasInscritas = new javax.swing.JPanel();
        Inscribir_Persona = new javax.swing.JToggleButton();
        Eliminar_Persona = new javax.swing.JToggleButton();
        Actualizar_Persona = new javax.swing.JToggleButton();
        InscribirEstudiante = new javax.swing.JToggleButton();
        ActualizarEstudiante = new javax.swing.JToggleButton();
        InscribirDecano = new javax.swing.JToggleButton();
        ActualizarDecano = new javax.swing.JToggleButton();
        CursosProfesores = new javax.swing.JPanel();
        content_CursosProfesores = new javax.swing.JPanel();
        Inscribir_Profesores = new javax.swing.JToggleButton();
        toString_Profesores = new javax.swing.JButton();
        jPanel1 = new javax.swing.JPanel();
        CrearFaculdad = new javax.swing.JButton();
        ActualizarFacultad = new javax.swing.JButton();
        InscribirPrograma = new javax.swing.JButton();
        ActualizarPrograma = new javax.swing.JButton();
        InscripcionCurso = new javax.swing.JButton();
        InscripcionCurso1 = new javax.swing.JButton();
        content_AreaAdministrativa = new javax.swing.JPanel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLabel1.setText("BIENVENIDO");

        javax.swing.GroupLayout HomeLayout = new javax.swing.GroupLayout(Home);
        Home.setLayout(HomeLayout);
        HomeLayout.setHorizontalGroup(
            HomeLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(HomeLayout.createSequentialGroup()
                .addGap(214, 214, 214)
                .addComponent(jLabel1)
                .addContainerGap(728, Short.MAX_VALUE))
        );
        HomeLayout.setVerticalGroup(
            HomeLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, HomeLayout.createSequentialGroup()
                .addContainerGap(275, Short.MAX_VALUE)
                .addComponent(jLabel1)
                .addGap(259, 259, 259))
        );

        HOME.addTab("HOME", Home);

        javax.swing.GroupLayout content_PersonasInscritasLayout = new javax.swing.GroupLayout(content_PersonasInscritas);
        content_PersonasInscritas.setLayout(content_PersonasInscritasLayout);
        content_PersonasInscritasLayout.setHorizontalGroup(
            content_PersonasInscritasLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 858, Short.MAX_VALUE)
        );
        content_PersonasInscritasLayout.setVerticalGroup(
            content_PersonasInscritasLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
        );

        Inscribir_Persona.setText("Incribir Profesor");
        Inscribir_Persona.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Inscribir_PersonaActionPerformed(evt);
            }
        });

        Eliminar_Persona.setLabel("Eliminar");
        Eliminar_Persona.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Eliminar_PersonaActionPerformed(evt);
            }
        });

        Actualizar_Persona.setText("Actualizar Profesor");
        Actualizar_Persona.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Actualizar_PersonaActionPerformed(evt);
            }
        });

        InscribirEstudiante.setText("Inscribir Estudiante");
        InscribirEstudiante.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                InscribirEstudianteActionPerformed(evt);
            }
        });

        ActualizarEstudiante.setText("Actualizar Estudiante");
        ActualizarEstudiante.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ActualizarEstudianteActionPerformed(evt);
            }
        });

        InscribirDecano.setText("Inscribir Decano");

        ActualizarDecano.setText("Actualizar Decano");

        javax.swing.GroupLayout PersonasInscritasLayout = new javax.swing.GroupLayout(PersonasInscritas);
        PersonasInscritas.setLayout(PersonasInscritasLayout);
        PersonasInscritasLayout.setHorizontalGroup(
            PersonasInscritasLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, PersonasInscritasLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(PersonasInscritasLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                    .addComponent(InscribirDecano, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(Eliminar_Persona, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(Actualizar_Persona, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(Inscribir_Persona, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(InscribirEstudiante, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(ActualizarEstudiante, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(ActualizarDecano, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(content_PersonasInscritas, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        PersonasInscritasLayout.setVerticalGroup(
            PersonasInscritasLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(PersonasInscritasLayout.createSequentialGroup()
                .addComponent(content_PersonasInscritas, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
            .addGroup(PersonasInscritasLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(Inscribir_Persona)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(Actualizar_Persona)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(InscribirEstudiante)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(ActualizarEstudiante)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(InscribirDecano)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(ActualizarDecano)
                .addGap(18, 18, 18)
                .addComponent(Eliminar_Persona)
                .addContainerGap(335, Short.MAX_VALUE))
        );

        Inscribir_Persona.getAccessibleContext().setAccessibleName("Inscribir");

        HOME.addTab("Personas Inscritas", PersonasInscritas);

        content_CursosProfesores.setPreferredSize(new java.awt.Dimension(778, 544));

        javax.swing.GroupLayout content_CursosProfesoresLayout = new javax.swing.GroupLayout(content_CursosProfesores);
        content_CursosProfesores.setLayout(content_CursosProfesoresLayout);
        content_CursosProfesoresLayout.setHorizontalGroup(
            content_CursosProfesoresLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 778, Short.MAX_VALUE)
        );
        content_CursosProfesoresLayout.setVerticalGroup(
            content_CursosProfesoresLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
        );

        Inscribir_Profesores.setLabel("Inscribir");
        Inscribir_Profesores.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Inscribir_ProfesoresActionPerformed(evt);
            }
        });

        toString_Profesores.setLabel("toString");
        toString_Profesores.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                toString_ProfesoresActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout CursosProfesoresLayout = new javax.swing.GroupLayout(CursosProfesores);
        CursosProfesores.setLayout(CursosProfesoresLayout);
        CursosProfesoresLayout.setHorizontalGroup(
            CursosProfesoresLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, CursosProfesoresLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(CursosProfesoresLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(Inscribir_Profesores, javax.swing.GroupLayout.DEFAULT_SIZE, 111, Short.MAX_VALUE)
                    .addComponent(toString_Profesores, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 116, Short.MAX_VALUE)
                .addComponent(content_CursosProfesores, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
        );
        CursosProfesoresLayout.setVerticalGroup(
            CursosProfesoresLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(CursosProfesoresLayout.createSequentialGroup()
                .addComponent(content_CursosProfesores, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
            .addGroup(CursosProfesoresLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(Inscribir_Profesores)
                .addGap(18, 18, 18)
                .addComponent(toString_Profesores)
                .addContainerGap(480, Short.MAX_VALUE))
        );

        HOME.addTab("Cursos Profesores", CursosProfesores);

        CrearFaculdad.setText("Crear Facultad");
        CrearFaculdad.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                CrearFaculdadActionPerformed(evt);
            }
        });

        ActualizarFacultad.setText("Actualizar/Eliminar Facultad");
        ActualizarFacultad.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ActualizarFacultadActionPerformed(evt);
            }
        });

        InscribirPrograma.setText("Inscribir Programa");
        InscribirPrograma.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                InscribirProgramaActionPerformed(evt);
            }
        });

        ActualizarPrograma.setText("Actualizar/Eliminar Programa");
        ActualizarPrograma.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ActualizarProgramaActionPerformed(evt);
            }
        });

        InscripcionCurso.setText("Inscribir Curso");
        InscripcionCurso.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                InscripcionCursoActionPerformed(evt);
            }
        });

        InscripcionCurso1.setText("Actualizar/Eliminar Curso");
        InscripcionCurso1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                InscripcionCurso1ActionPerformed(evt);
            }
        });

        content_AreaAdministrativa.setMinimumSize(new java.awt.Dimension(778, 544));

        javax.swing.GroupLayout content_AreaAdministrativaLayout = new javax.swing.GroupLayout(content_AreaAdministrativa);
        content_AreaAdministrativa.setLayout(content_AreaAdministrativaLayout);
        content_AreaAdministrativaLayout.setHorizontalGroup(
            content_AreaAdministrativaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
        );
        content_AreaAdministrativaLayout.setVerticalGroup(
            content_AreaAdministrativaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
        );

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(ActualizarFacultad, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(CrearFaculdad, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(InscribirPrograma, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(ActualizarPrograma, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(InscripcionCurso, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(InscripcionCurso1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(content_AreaAdministrativa, javax.swing.GroupLayout.PREFERRED_SIZE, 777, Short.MAX_VALUE)
                .addGap(36, 36, 36))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(CrearFaculdad)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(ActualizarFacultad)
                .addGap(35, 35, 35)
                .addComponent(InscribirPrograma)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(ActualizarPrograma)
                .addGap(35, 35, 35)
                .addComponent(InscripcionCurso)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(InscripcionCurso1)
                .addContainerGap(318, Short.MAX_VALUE))
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addComponent(content_AreaAdministrativa, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );

        HOME.addTab("Area Administrativa", jPanel1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(HOME)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(HOME)
        );

        HOME.getAccessibleContext().setAccessibleName("HOME");

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void InscripcionCurso1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_InscripcionCurso1ActionPerformed
        ManejoCurso Panel = new ManejoCurso();
        ShowPanel(Panel ,content_AreaAdministrativa);
    }//GEN-LAST:event_InscripcionCurso1ActionPerformed

    private void ActualizarProgramaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ActualizarProgramaActionPerformed
        ManejoPrograma Panel = new ManejoPrograma();
        ShowPanel(Panel ,content_AreaAdministrativa);
    }//GEN-LAST:event_ActualizarProgramaActionPerformed

    private void InscribirProgramaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_InscribirProgramaActionPerformed
        IncribirPrograma Panel = new IncribirPrograma();
        ShowPanel(Panel ,content_AreaAdministrativa);
    }//GEN-LAST:event_InscribirProgramaActionPerformed

    private void ActualizarFacultadActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ActualizarFacultadActionPerformed
        ManejoFacultad Panel = new ManejoFacultad();
        ShowPanel(Panel ,content_AreaAdministrativa);
    }//GEN-LAST:event_ActualizarFacultadActionPerformed

    private void CrearFaculdadActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_CrearFaculdadActionPerformed
        IncribirFacultad Panel = new IncribirFacultad();
        ShowPanel(Panel ,content_AreaAdministrativa);
    }//GEN-LAST:event_CrearFaculdadActionPerformed

    private void toString_ProfesoresActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_toString_ProfesoresActionPerformed
        
    }//GEN-LAST:event_toString_ProfesoresActionPerformed

    private void Inscribir_ProfesoresActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Inscribir_ProfesoresActionPerformed
        
    }//GEN-LAST:event_Inscribir_ProfesoresActionPerformed

    private void ActualizarEstudianteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ActualizarEstudianteActionPerformed
        ActualizarEstudiante Panel = new ActualizarEstudiante();
        ShowPanel(Panel ,content_PersonasInscritas);
    }//GEN-LAST:event_ActualizarEstudianteActionPerformed

    private void InscribirEstudianteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_InscribirEstudianteActionPerformed
        IncribirEstudiante Panel = new IncribirEstudiante();
        ShowPanel(Panel ,content_PersonasInscritas);
    }//GEN-LAST:event_InscribirEstudianteActionPerformed

    private void Actualizar_PersonaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Actualizar_PersonaActionPerformed
        ActualizarProfesor Panel = new ActualizarProfesor();
        ShowPanel(Panel,content_PersonasInscritas);
    }//GEN-LAST:event_Actualizar_PersonaActionPerformed

    private void Eliminar_PersonaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Eliminar_PersonaActionPerformed
        Eliminar_Persona Panel = new Eliminar_Persona();
        ShowPanel(Panel,content_PersonasInscritas);
    }//GEN-LAST:event_Eliminar_PersonaActionPerformed

    private void Inscribir_PersonaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Inscribir_PersonaActionPerformed
        IncribirProfesor Panel = new IncribirProfesor ();
        ShowPanel(Panel ,content_PersonasInscritas);
    }//GEN-LAST:event_Inscribir_PersonaActionPerformed

    private void InscripcionCursoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_InscripcionCursoActionPerformed
        IncribirCurso Panel = new IncribirCurso();
        ShowPanel(Panel ,content_AreaAdministrativa);
    }//GEN-LAST:event_InscripcionCursoActionPerformed

    private void ShowPanel(JPanel panel,JPanel content){
        panel.setSize(778, 544);
        panel.setLocation(0,0);
        
        content.removeAll();
        content.add(panel, BorderLayout.CENTER);
        content.revalidate();
        content.repaint();
    }
    
    
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(GIU_Principal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(GIU_Principal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(GIU_Principal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(GIU_Principal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new GIU_Principal().setVisible(true);
            }
        });
    }
    
    

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JToggleButton ActualizarDecano;
    private javax.swing.JToggleButton ActualizarEstudiante;
    private javax.swing.JButton ActualizarFacultad;
    private javax.swing.JButton ActualizarPrograma;
    private javax.swing.JToggleButton Actualizar_Persona;
    private javax.swing.JButton CrearFaculdad;
    private javax.swing.JPanel CursosProfesores;
    private javax.swing.JToggleButton Eliminar_Persona;
    private javax.swing.JTabbedPane HOME;
    private javax.swing.JPanel Home;
    private javax.swing.JToggleButton InscribirDecano;
    private javax.swing.JToggleButton InscribirEstudiante;
    private javax.swing.JButton InscribirPrograma;
    private javax.swing.JToggleButton Inscribir_Persona;
    private javax.swing.JToggleButton Inscribir_Profesores;
    private javax.swing.JButton InscripcionCurso;
    private javax.swing.JButton InscripcionCurso1;
    private javax.swing.JPanel PersonasInscritas;
    private javax.swing.JPanel content_AreaAdministrativa;
    private javax.swing.JPanel content_CursosProfesores;
    private javax.swing.JPanel content_PersonasInscritas;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JButton toString_Profesores;
    // End of variables declaration//GEN-END:variables

}

